name: 'Terraform Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement à déployer (dev ou prod)'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        # On utilise une clé différente pour le tfstate selon l'environnement
        terraform init \
          -backend-config="key=${{ github.event.inputs.environment }}.terraform.tfstate"

    - name: Terraform Plan
      run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve